name: Tests
on: [push, pull_request]
jobs:
  lumen-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        operating-system: ['ubuntu-latest']
        php-versions: ['8.0']
        phpunit-versions: ['latest']
        include:
          - operating-system: 'ubuntu-latest'
            php-versions: '8.0'
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_DATABASE: bookr_testing
          MYSQL_HOST: 127.0.0.1
          MYSQL_USER: homestead
          MYSQL_PASSWORD: secret
          MYSQL_ROOT_PASSWORD: rootpass
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - uses: nanasess/setup-php@master
        with:
          php-version: '8.0'
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          DB_USERNAME: homestead
          DB_PASSWORD: secret
          file_name: .env
          fail_on_empty: false
      - name: Update Composer
        run: sudo composer self-update 1.10.15 --no-interaction
      - name: Run Composer Install
        run: composer install --no-interaction
      - name: run migrations
        run: php artisan migrate --force
      - name: run phpstan
        run: vendor/bin/phpstan
      - name: run tests
        run: vendor/bin/phpunit
